title: "Wei Tu, PhD"
name: "Wei Tu"
email: "wei.tu@queensu.ca"
description: "Senior Biostatistician & Assistant Professor | Clinical trials, statistical learning, biomarkers"
url: "https://weitumuch.github.io"
baseurl: ""
include:
  - _pages

# Social
google_scholar_id: "3loMCisAAAAJ"

# Build
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:title/

# ✅ Header navigation
header_pages:
  - _pages/about.md
  - _pages/research.md
  - _pages/teaching.md
  - _pages/team.md
  - _pages/cv.md

# Theme
theme: minima
permalink: pretty

# Hide the "View on GitHub" header link
github:
  is_project_page: false
