title: "Wei Tu, PhD"
name: "Wei Tu"
email: "wei.tu@queensu.ca"
description: "Senior Biostatistician & Assistant Professor | Clinical trials, statistical learning, biomarkers"
url: ""  # e.g., https://weitu.github.io once live
baseurl: ""
include:
  - _pages
  
# Social/usernames
github_username: 
google_scholar_id: "3loMCisAAAAJ"   # add your ID
orcid: ""               # add your ORCID
twitter_username: ""

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:title/

# Navigation
nav_pages:
  - index.md
  - _pages/research.md
  - _pages/teaching.md
  - _pages/team.md
  - _pages/cv.md

# Appearance
theme: minima
permalink: pretty
